### ISSUE TITLE
Status for projects (folder) within same repository

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#128]
Post GH statuses based on projects (aka specific folders) instead of the entire repository.

> More coming soon

**Comment by stevepeak** [comment]
Added to `codecov.yml`

```
coverage:
  status:
    project:
      custom_name:
        target: 80%
        paths:
          - app/project_1
```

> This will report coverage from contents only found in `app/project_1` folder. The context will be `codecov/project/custom_name`

**Comment by szweier** [comment]
Would we be able to list multiple projects in this yml? The setup I'm currently working on is a workspace with a number of projects in it.

**Comment by stevepeak** [comment]
@szweier yes, you can :+1: This works for all features, here is an example:

```
coverage:
  status:
    project:
      project_1:
        target: 80%
        paths: app/project_1
      project_2:
        target: 80%
        paths: app/project_2
```

Now you will see two commit status: `codecov/project/project_1` and `codecov/project/project_2` as the context.
