### ISSUE TITLE
Inconsistent documentation for ignore

### ISSUE THREAD

**Issue by pitrou** [codecov/support#166]
The suggested settings for my repo are:
```
comment:
  layout: header, changes, diff
coverage:
  ignore:
  - numba/cuda/.*
  - numba/hsa/.*
```

The doc for `ignore` says:

> List of regular expression patterns that will match folders and files removing matches from reports and noticiations.
> 
> Removing test folders
> 
> ignore:
> - `tests/*`
> - `*/vendor/*`
> 
> Ignore specific file patterns
> 
> ignore:
> - `*/module_*`

Notice how the description says "regular expression patterns" but the example uses shell-like glob patterns.
