### ISSUE TITLE
Disabling status checks via YML doesn't seem to work

### ISSUE THREAD

**Issue by pganssle** [codecov/support#186]
I'm trying to get codecov to have only project requirements, and only communicate via the status hooks, not a code comment. Here's the YAML file I'm using:

```yaml
coverage:
  ci:
    - travis
  status:
    patch: false
    changes: false
    project:
      default:
        target: '80'

comment: false
```

Here's a test PR to demonstrate it: pganssle/dateutil-test-codecov#4

How do I get it to only require the 80% project coverage and not the patch or changes coverage?

Also, as a side note, in that one, the `comment: false` seems to be working, but it *was* commenting on pganssle/dateutil-test-codecov#3 and pganssle/dateutil-test-codecov#2, when I had `comment: False` and `comment: off`, but was using both travis and appveyor. Not sure what's up with that.

**Comment by skirpichev** [comment]
Same for me, see e.g. [this](https://github.com/codecov/support/issues/164#issuecomment-216038264).

**Comment by stevepeak** [comment]
@pganssle the config above is not valid, you can verify this at

```
curl --data-binary @codecov.yml https://codecov.io/validate
```

You do not need to include travis. If you want to ignore appveyer then:
```yaml
codecov:
  ci:
    - !ci.appveyor.com
coverage:
  status:
    patch: false
    changes: false
    project:
      default:
        target: '80'

comment: false
```

**Comment by pganssle** [comment]
@stevepeak Thanks for the information. I don't want to ignore appveyor, I want to make sure that codecov _waits_ for appveyor (Appveyor is much slower than Travis, so codecov is setting a "failed" status because all the Windows-specific code doesn't appear in the tests).

**Comment by stevepeak** [comment]
Ok, waiting for AppVeyor will occur by default. So lets use this:

```yaml
coverage:
  status:
    patch: false
    changes: false
    project:
      default:
        target: '80'

comment: false
```

**Comment by pganssle** [comment]
How does it know that I'm using Appveyor? I think that Travis finishes before Appveyor starts.

**Comment by stevepeak** [comment]
Codecov monitors the commits statuses on your repository. As long as AppVeyor is posting a status then Codecov will wait for it to complete.

**Comment by pganssle** [comment]
I see. Thanks for the info. The validation thing is very useful.

FYI, under `n_builds`, it says `Integar` instead of `Integer`.

**Comment by stevepeak** [comment]
Thanks! 👍

**Comment by skirpichev** [comment]
@stevepeak, suggested solution doesn't work.

See: https://github.com/skirpichev/omg/pull/269.  Both changes and comments are set to false, but there is a comment from codecov-io and active codecov/changes status.  YML file is correct, according to your tool:
```
$ cat .codecov.yml 
coverage:
  precision: 0
  round: down
  status:
    patch:
      default:
        target: 90
    project:
      default:
        threshold: 1%
    changes: false
comment: false
$ curl -s --data-binary @.codecov.yml https://codecov.io/validate|head -1
Valid!
```

@pganssle, could you repeat your test with fixed codecov.yml?  And then reopen issue if it's valid for you.

**Comment by stevepeak** [comment]
@skirpichev `codecov/changes` are now disabled by default. How have recent commits been?

**Comment by skirpichev** [comment]
Yes, it seems changes now are disabled.

BTW, my "changes: false" setting was incorrect?  Is it redundant now (same question for "comment: false")?

**Comment by stevepeak** [comment]
Your setting was accurate. And it is redundant now. You can remove `changes: false` as its default now.

**Comment by zurfyx** [comment]
I managed to solve it, so I thought it might as well share my solution:
The YAML filename has to be exactly `codecov.yml`, not `.codecov.yml`.

```
coverage:
  status:
    project: off
    patch: off

comment: false
```

`status` removes ticks and crosses next to each commit.
`comment` is to remove pull requests coverage comments.
