### ISSUE TITLE
How I can set a minimal limit on PR merge some-branch=>master ?

### ISSUE THREAD

**Issue by ryukinix** [codecov/support#211]
Example: www.github.com/ryukinix/decorating/pull/5 I wants to setup a minimal coverage, instead get the target based on the branch. Is possible do that? (passing with 90, instead 95 of target)

**Comment by stevepeak** [comment]
By default Codecov will set the status based on `branch >= master`. But you can also set a manual target:

```
coverage:
  status:
    project:
      default:
        target: 90%
```
