### ISSUE TITLE
Multi-module maven project

### ISSUE THREAD

**Issue by automatictester** [codecov/support#230]
I have a multi-module Maven project stored in a single Git repo. Please note it has nothing to do with Git submodules. How can I track coverage on module level, rather than repo level? I want to know separate coverage stats for every module, not an aggregated one for entire project.

**Comment by stevepeak** [comment]
Hey @automatictester you certainly can :) In your codecov.yml you can create custom statuses to specific folders. Here is an example:

```
coverage:
  status:
    project:
      custom_a:  # you can create many custom statuses
        paths:
          - "path/to/module"
        target: 90%
```
