### ISSUE TITLE
Waiting for CI to complete ...

### ISSUE THREAD

**Issue by jeppefrandsen** [codecov/support#312]
We have an issue with one of our repositories that it keeps waiting for CI to complete. It has found the parent commit but does not update the GitHub status. Furthermore it has taken almost 30 minutes before it finds the uploaded report. The commit can be found here: 
https://codecov.io/gh/bang-olufsen/ase/commit/0170891446bd20a8bd72eb7f4b9e3837445f4a0d/builds

I have tried various options to fix this. See the codecov.yml below:

```
codecov:
  bot: <name removed>
  ci:
    - !app.shippable.com
  notify:
    require_ci_to_pass: false
    countdown: 15
    delay: 15

coverage:
  status:
    project: false
    patch:
      default:
        target: 80%

comment: false
```

**Comment by stevepeak** [comment]
@jeppefrandsen thank you for reporting. You almost got it 👍 So you may disable CI checking altogether like this:

```yaml
codecov:
  bot: <name removed>
  notify:
    require_ci_to_pass: false
    # countdown: 15
    # delay: 15
    after_n_builds: 1  # send notifications and complete cc build after 1 upload

coverage:
  status:
    project: false
    patch:
      default:
        target: 80%

comment: false
```
