### ISSUE TITLE
Exclusions for project status not working

### ISSUE THREAD

**Issue by dopplershift** [codecov/support#330]
I can't seem to get the exclusions for paths for separate project statuses (as outlined [here](http://docs.codecov.io/docs/commit-status)) to work properly.

For instance on this [pull request](https://github.com/Unidata/MetPy/pull/274) I've modified my `codecov.yml` file to be:
```yaml
codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    patch:
      default:
        target: '80'
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    project:
      default: false
      library:
        target: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
        paths:
          - "/metpy"
          - "!/metpy/calc/tests/"
          - "!/metpy/gridding/tests/"
          - "!/metpy/io/tests/"
          - "!/metpy/plots/tests/"
      tests:
        target: 100%
        paths: "/metpy/*/tests/"

comment: off
```
This is the first time I'm including the tests as part of the coverage report. Despite the exclusion specified for the "library" project, I still see a large bump in the test coverage in the status for the "library" project on the pull request (+1.43% to > 97%) due to the inclusions of the lines of tests in the coverage number. I've tried many iterations on the exclusion lines for the "library" project, but I can't seem to get those tests excluded. (In my ideal world, this would work with some relatively simple wildcard.)

Am I missing something?

**Comment by stevepeak** [comment]
Thank you for asking. Your configuration is valid 👍 Nice job.

Can you set the paths to the following. I'll need to fix our paths to strip the first `/` character.

```
        paths:
          - "metpy/.*"
          - "!metpy/calc/tests/.*"
          - "!metpy/gridding/tests/.*"
          - "!metpy/io/tests/.*"
          - "!metpy/plots/tests/.*"
      
      paths: "metpy/.*/tests/.*"
```

**Comment by dopplershift** [comment]
Still the same results.

**Comment by dopplershift** [comment]
Setting:
```yaml
    project:
      library:
        paths:
          - "metpy/calc/*.py"
```
Results in a coverage of 99.75% (just that one module). Trying then:
```yaml
    project:
      library:
        paths:
          - "metpy/calc/*.py"
          - "!metpy/calc/tests/*.py"
```
Gives me the same 99.75% coverage.
