### ISSUE TITLE
YML Detection not working

### ISSUE THREAD

**Issue by rianquinn** [codecov/support#331]
This is my Travic setup:

```
  - os: linux
    env:
      - TEST="Codecov"
    services:
      - docker
    before_install:
      - cd ..
      - git clone https://github.com/bareflank/hypervisor.git
      - mv extended_apis hypervisor/
      - cd hypervisor
    install:
      - travis_wait 40 ./tools/scripts/setup_ubuntu.sh
    script:
      - COVERALLS=true make
      - make test
    after_success:
      - cd extended_apis
      - wget https://codecov.io/bash
      - mv bash codecov.sh
      - chmod +x codecov.sh
      - ./codecov.sh -s . -p ../makefiles/extended_apis/ -a '\-lp'
```

The YML configuration file is not detected by the bash script. The problem is with this line:

```bash
yaml=$(cd "$proj_root" && git ls-files "*codecov.yml" 2>/dev/null || hg locate "*codecov.yml" 2>/dev/null || find . -name "*codecov.yml" 2>/dev/null || echo '')
```

proj_root in this case is the build location and not the git_root location. I tried copying the config to "../makefiles/extended_apis/" but the above bash code doesn't seem to work right as the ` find . -name "*codecov.yml" 2>/dev/null` part never gets a chance to execute. I can get it to work, but I have to patch the bash script to fix the issue. 

- Changing proj_root to git_root fixes the issue
- Getting rid of `git ls-files "*codecov.yml" 2>/dev/null || hg locate "*codecov.yml" 2>/dev/null` fixes the issue too so that the `find . -name....` part works. 

Not exactly sure what you want to do here
