### ISSUE TITLE
Add patch size test in addition to pct coverage

### ISSUE THREAD

**Issue by acima** [codecov/support#361]
For small patches, per cent coverage is too gross a measure.  A patch of one line requires 100% test coverage always.  Your already have the size of the patch, it should be easy to say  'patch coverage > 80% or patch size < 8 lines'

**Comment by stevepeak** [comment]
Would this work:

```yml
coverage:
  status:
    patch:
      default:
        require_n_lines_changed: 8
```
> Feel free to suggest another key or format.
