### ISSUE TITLE
Flags with no uploads can use global data

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#366]
> Concerning Codecov Flags: http://docs.codecov.io/docs/flags

### Issue
If no upload was flagged via `-F foobar` than `#foobar` is empty.

```yaml
# codecov.yml
flags:
  foobar:
    paths:
      - app/foo/
      - app/bar/
```

### Current Policy
**IF** uploads to `-F foobar` **THEN** only use that report data for `#foobar`. 

### New Policy
**IF** no uploads to `-F foobar` **THEN** use all report data to generate `#foobar`.
