### ISSUE TITLE
Notifications: IRC: documentation is missing?

### ISSUE THREAD

**Issue by LebedevRI** [codecov/support#379]
Continuation of #60
https://github.com/codecov/support/issues/60#issuecomment-165982817 says that it should be deployed by now.
But https://docs.codecov.io/docs/notifications does not say anything about IRC

**Comment by ELLIOTTCABLE** [comment]
Still waiting on this!

**Comment by greenteamsite** [comment]
Find here:

https://github.com/codecov/support/wiki/Codecov-Yaml#full-yaml

**Comment by LebedevRI** [comment]
@stevepeak is this functionality present or not?
```
$ cat codecov.yml 
codecov:
  notify:
    require_ci_to_pass: true
    irc:
      default:
        server: "chat.freenode.net"
        channel: '#rawspeed'
$ cat codecov.yml | curl --data-binary @- https://codecov.io/validate
Invalid value {'irc': {'default': {'server': 'chat.freenode.net', 'channel': '#rawspeed'}}} (dict): additional properties: ['irc'] (at codecov['notify'])
```

**Comment by stevepeak** [comment]
Hi, the function is present. Use this format:

```yaml
coverage:
  notify:
    irc:
      default:  # customer title
        server: "chat.freenode.net"
        channel: string
        password: string
        nickserv_password: string
        notice: boolean
```

> Thank you for your patience.

Let me know if you have questions following up on this.
