### ISSUE TITLE
Combining model flags and Patch treshold?

### ISSUE THREAD

**Issue by ankanx** [codecov/support#465]
Hi, ive been trying to combine having flags that sort out specific paths to cover with having a threshold of 5% that should be allowing a flexible coverage of 5% on pull requests etc to master?

what would the pattern be for this?
Currently looking like this:

[codecov.txt](https://github.com/codecov/support/files/1567742/codecov.txt)

Thanks in advance!

**Comment by stevepeak** [comment]
There is a formatting error in your yaml

```
cat codecov.yml | curl --data-binary @- https://codecov.io/validate
```

```yaml
coverage:
  patch:
  default:
````
The `default` needs to be indented under `patch`. And `patch` needs to be under `coverage.status`

**Comment by ankanx** [comment]
Like this?

[codecov.txt](https://github.com/codecov/support/files/1567804/codecov.txt)

**Comment by stevepeak** [comment]
Actually like this

```yaml
coverage:
    status:
      patch:                     # pull requests only: this commit status will measure the                       # adjusted are covered at least X%.
        default:
          enabled: yes             # must be yes|true to enable this status
          target: 80%              # specify the target "X%" coverage to hit         # -> see "branch patterns" below
          threshold: 5%         # allowed to drop X% and still result in a "success" commit status
          if_no_uploads: error     # will post commit status of "error" if no coverage reports we uploaded                         # options: success, error, failure
          if_not_found: success
          if_ci_failed: error
      project:
        default: off
        model:
          target: 10%
          flags: model
        extendedFunictionality:
          target: 90%
          flags: extendedFunictionality
        playback:
          target: 10%
          flags: playback
        ui:
          target: 10%
          flags: ui

# Each flag has a target coverage rate to reach

flags:
  # filter the folder(s) you wish to measure by that flag
  model:
    # only include files in the model folder
    paths:
      - ./mobile/src/main/java/com/example/android/uamp/model
  extendedFunictionality:
      # only include files in the extendedFunctionality folder
    paths:
      - ./mobile/src/main/java/com/example/android/uamp/extendedFunictionality/view
      - ./mobile/src/main/java/com/example/android/uamp/extendedFunictionality/utils/database
      - ./mobile/src/main/java/com/example/android/uamp/extendedFunictionality/utils/application/DatabaseUtils.java
      - ./mobile/src/main/java/com/example/android/uamp/extendedFunictionality/utils/mediaAnalytics
      - ./mobile/src/main/java/com/example/android/uamp/extendedFunictionality/utils/*.java
      - ./mobile/src/main/java/com/example/android/uamp/extendedFunictionality/model
  playback:
      # only include files in the playback folder
    paths:
      - ./mobile/src/main/java/com/example/android/uamp/playback
  ui:
      # only include files in the ui folder
    paths:
      - ./mobile/src/main/java/com/example/android/uamp/ui
```
