### ISSUE TITLE
Filterting coverage by folder

### ISSUE THREAD

**Issue by yelizariev** [codecov/support#497]
I have one coverage test (coverage file) and I'm trying to assign flags to files depending on its folders.

In the end, I want to get reports like following

* res_config.py is covered for 90%
* files in  "*/controllers/" are covered for 70%
* files in "*/tests/" are covered for 99%
* rest files (backend) for 55%

**How I'm trying to do it.**

I send coverage file with four flags (``-F backend controllers tests res_config``) and then apply following yaml config:

```
flags:
  backend:
    paths:
      - "!*/controllers/"
      - "!*/tests/"
      - "!**/res_config.py$"
  controllers:
    paths:
      - "*/controllers/"
  tests:
    paths:
      - "*/tests/"
  res_config:
    paths:
      - "**/res_config.py$"
```

**What I get**

It's either every file has all flags or no files are flagged (probably it's another not related issue).

**The question**

Do I understand idea of  [# filter the folder(s) you wish to measure by that flag](https://docs.codecov.io/docs/flags#section-create-custom-notifications) right I can get the reports I want with proper configuration?
